#!/bin/bash
VFD=mtximage

echo copying mtximage...
cp mtximage_copy mtximage

as86 -o ts.o ts.s
bcc  -c -ansi t.c
ld86 -d -o mtx ts.o t.o mtxlib /usr/lib/bcc/libc.a

echo showing size:
ls -l mtx

mount -o loop $VFD /mnt
cp mtx /mnt/boot
umount /mnt
rm *.o mtx

(cd USER; mku u1)

echo done

qemu-system-i386 -fda mtximage -no-fd-bootchk
